### PR TITLE
Don't put upper bounds on dependency versions

### PR DESCRIPTION
**Pull request by propertone**
This is considered a bad practice, especially for libraries.
See https://iscinumpy.dev/post/bound-version-constraints/ for a discussion.

This reverts 2c4367b016cb82eafddb310864b72a047b9bb735

### CODE REVIEW

**Comment by propertone** [comment]
@jab @mkomitee

**Comment by mkomitee** [comment]
Ping @twosigmajab -- I suspect @propertone meant to ping you last week as well --- unless you and @jab are the same person.

I'm okay with this, but before we move forward I'd like to know why we thought it was necessary in https://github.com/deshaw/wsgi-kerberos/commit/2c4367b016cb82eafddb310864b72a047b9bb735. I suspect it has something to do with changes to the kerberos library which caused issues, and before we revert, I'd like to know for certain that it won't cause issues for our users today.

**Comment by jab** [comment]
Same person, @twosigmajab is just the account I used from company laptops.

I just checked https://pypi.org/project/kerberos/#history, https://github.com/apple/ccs-pykerberos/blob/master/setup.py, https://github.com/apple/ccs-pykerberos/milestones, etc. and there still isn't yet any mention of a v2 coming out in the future, let alone some known breaking change in v2 that we were concerned about in 2019.

My thinking in 2c4367b016cb82eafddb310864b72a047b9bb735 was merely an overly-conservative interpretation of semver. Note that this change predates by several years the now-more-common wisdom in the post that @propertone linked to above. (Since you merged that change, is that how you used to, and also now no longer, interpret semver too?)

Thanks for being extra careful and checking first!

**Comment by mkomitee** [comment]
I tend to be conservative about these kinds of things and I'm not 100% I agree with the referenced article, and think protecting our users from API breaking changes in the underlying kerberos library is a Good Thing(tm) even if impractical, but I'm willing to defer to @propertone if he thinks this is the right move as he's been paying closer attention to the community than I.

**Review by mkomitee — APPROVED** [review]
If you're confident this is safe with the current released versions of the library, and if this is how the community is evolving, then LGTM.

**Comment by propertone** [comment]
Yeah, the change should be completely safe and a no-op right now. In the (unlikely) chance that a new major version of the Kerberos library is released, it would be better to give users the ability to upgrade it rather than preventing it altogether.

**Pull request merged**
